export const EXPERIENCE_CONSTANTS = [
  {
    id: 0,
    img: "/cto-global.jpeg",
    role: "Fullstack Web Developer",
    company: "Comfac Tech Options GS",
    date: "April 2019 - Present",
    description:
      "Develop and upkeep essential elements integral to Deliveries PH App's frontend and backend infrastructure, spanning the entire product suite. Collaborate closely with diverse teams, including developers, designers, and product managers, to integrate and advocate best standards in web accessibility.",
    skills: [
      "React",
      "Docker",
      "Node JS",
      "Express JS",
      "MongoDB",
      "PostgreSQL",
      "Firebase",
      "Tailwind CSS",
      "Bitbucket",
      "Jira",
      "Ant Design",
      "Material UI",
      "Typescript",
      "React Query",
      "Redux",
      "Vite",
      "CI/CD"
    ],
    url: "https://web.deliveries.ph/login",
  },
  {
    id: 1,
    img: "/global-cis.jpeg",
    role: "Web Developer",
    company: "Global CIS Ltd",
    date: "July 2016 - October 2018",
    description:
      "Create website layout interfaces in alignment with the company's requirements. Enhance and update code and design of existing web applications to improve functionality and modernize interfaces. Responsible for ongoing maintenance of websites, addressing bugs and errors.",
    skills: [
      "Javascript",
      "JQuery",
      "Bootstrap",
      "ColdFusion",
      "Oracle",
      "HTML",
      "CSS",
    ],
    url: "https://www.global-creditreports.com/",
  },
  {
    id: 2,
    img: "/ti.jpeg",
    role: "Technical Support",
    company: "Texas Instruments Inc",
    date: "October 2013 - March 2016",
    description:
      "Supports and resolves wafermap issues by analyzing the customer’s concern; determining the cause of the problem; and executing the needed steps to resolve the problem.",
    skills: [],
  },
];
